language: python
python:
  - "2.7"    
  - "3.6"
addons:
  apt:
    packages:
      - oracle-java8-installer
install:
  - pip install pylint==1.9.3
  - pylint --version
  - |
      export ECLIPSE_TAR=$TRAVIS_BUILD_DIR/../eclipse.tar.gz
      wget http://archive.eclipse.org/eclipse/downloads/drops4/R-4.5.2-201602121500/eclipse-SDK-4.5.2-linux-gtk-x86_64.tar.gz -O $ECLIPSE_TAR
      tar -C $TRAVIS_BUILD_DIR/.. -xf $ECLIPSE_TAR
      export ECLIPSE_EXE=$TRAVIS_BUILD_DIR/../eclipse/eclipse
      export JDT=$TRAVIS_BUILD_DIR/ecj.jar
      wget http://www.eclipse.org/downloads/download.php?file=/eclipse/downloads/drops4/R-4.5.2-201602121500/ecj-4.5.2.jar -O $JDT
script: ./mx --strict-compliance gate --strict-mode
